version: '3'

services:
  server:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - 8000:300

  openalpr:
    build:
      context: .
      dockerfile: openalpr/Dockerfile
    ports:
      - 8001:301