version: '3'

services:
  server1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:300

  openalpr:
    container_name: openalpr
    image: openalpr/commercial-agent:latest
    volumes:
      - /home/cctv2/openalpr/config/:/etc/openalpr/
      - /home/cctv2/openalpr/images/:/var/lib/openalpr/
    restart: always
    cap_add:
      - SYS_NICE